### ISSUE TITLE
PDF not loading

### ISSUE THREAD

**Issue by molcsab** [hugomyb/filament-media-action#2]
### What happened?

Hi, I have tried your plugin, and it works well in most cases, except when I try to view a pdf. 

### How to reproduce the bug

The loading indicator is spinning indefinitely. 

I have tried the following solution, and it works, although I am sure it can be done better (I'm not a front-end guy):

```html
 @elseif ($mediaType === 'pdf')

        <iframe x-ref="mediaFrame" class="rounded-lg" src="{{ $media }}" type="application/pdf" width="100%" height="2000" @load.window="loading = false"></iframe>

```

### Package Version

3.1.0.0

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by hugomyb** [comment]
Hi, 

I don't have any problems with PDFs, maybe it's due to the fact that you're on Mac with Safari I suppose? I have no way of testing on Safari.

In any case, I've made some changes to the plugin and released a new release. Can you tell me if this has corrected your problem? 

Release : [v3.1.0.1](https://github.com/hugomyb/filament-media-action/releases/tag/v3.1.0.1)

**Comment by molcsab** [comment]
Hi, I have updated the package, but the PDF is still not loading, just the loading indicator is spinning.
Indeed, I am on a Mac, but on Chrome.

In Firefox the PDF is loaded, but the PDF does not take the full height of the modal (I use ->slideOver())

**Comment by hugomyb** [comment]
Ok I managed to reproduce the problem on chrome, I corrected it and it works correctly for me now. Can you update the package and confirm that the problem is solved? 

Also, I've slightly reworked the style for the PDFs so that they take up the correct height.

Release : [v3.1.0.2](https://github.com/hugomyb/filament-media-action/releases/tag/v3.1.0.2)

**Comment by molcsab** [comment]
Still not loading, now I get "No preview available", and sometimes the loading indicator is just spinning
![CleanShot 2024-07-31 at 12 02 04@2x](https://github.com/user-attachments/assets/e6f972e3-fbb3-4fc9-8d7d-4aaba82227fc)

**Comment by hugomyb** [comment]
I've updated the package again, and now I have no problems with either Chrome or Firefox, and the PDF loads perfectly. Is it good for you?

**Comment by hugomyb** [comment]
Nice! Glad you like it, thanks for your issue and sorry for the inconvenience.
